package com.woniu.godaji.pojo;

import java.math.BigDecimal;

public class B2cServicestatioinWare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer warepriceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.serviceStatioinID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer servicestatioinid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal wareprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String materialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column B2C_serviceStatioin_ware.CFDiscountValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal cfdiscountvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.warePriceID
     *
     * @return the value of B2C_serviceStatioin_ware.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWarepriceid() {
        return warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.warePriceID
     *
     * @param warepriceid the value for B2C_serviceStatioin_ware.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarepriceid(Integer warepriceid) {
        this.warepriceid = warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.serviceStatioinID
     *
     * @return the value of B2C_serviceStatioin_ware.serviceStatioinID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getServicestatioinid() {
        return servicestatioinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.serviceStatioinID
     *
     * @param servicestatioinid the value for B2C_serviceStatioin_ware.serviceStatioinID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setServicestatioinid(Integer servicestatioinid) {
        this.servicestatioinid = servicestatioinid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.wareID
     *
     * @return the value of B2C_serviceStatioin_ware.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.wareID
     *
     * @param wareid the value for B2C_serviceStatioin_ware.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.warePrice
     *
     * @return the value of B2C_serviceStatioin_ware.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getWareprice() {
        return wareprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.warePrice
     *
     * @param wareprice the value for B2C_serviceStatioin_ware.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareprice(BigDecimal wareprice) {
        this.wareprice = wareprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.materialID
     *
     * @return the value of B2C_serviceStatioin_ware.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.materialID
     *
     * @param materialid the value for B2C_serviceStatioin_ware.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setMaterialid(String materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column B2C_serviceStatioin_ware.CFDiscountValue
     *
     * @return the value of B2C_serviceStatioin_ware.CFDiscountValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCfdiscountvalue() {
        return cfdiscountvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column B2C_serviceStatioin_ware.CFDiscountValue
     *
     * @param cfdiscountvalue the value for B2C_serviceStatioin_ware.CFDiscountValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCfdiscountvalue(BigDecimal cfdiscountvalue) {
        this.cfdiscountvalue = cfdiscountvalue;
    }
}