package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class B2cServicestatioinWareExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public B2cServicestatioinWareExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWarepriceidIsNull() {
            addCriterion("warePriceID is null");
            return (Criteria) this;
        }

        public Criteria andWarepriceidIsNotNull() {
            addCriterion("warePriceID is not null");
            return (Criteria) this;
        }

        public Criteria andWarepriceidEqualTo(Integer value) {
            addCriterion("warePriceID =", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotEqualTo(Integer value) {
            addCriterion("warePriceID <>", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidGreaterThan(Integer value) {
            addCriterion("warePriceID >", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("warePriceID >=", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidLessThan(Integer value) {
            addCriterion("warePriceID <", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidLessThanOrEqualTo(Integer value) {
            addCriterion("warePriceID <=", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidIn(List<Integer> values) {
            addCriterion("warePriceID in", values, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotIn(List<Integer> values) {
            addCriterion("warePriceID not in", values, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidBetween(Integer value1, Integer value2) {
            addCriterion("warePriceID between", value1, value2, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotBetween(Integer value1, Integer value2) {
            addCriterion("warePriceID not between", value1, value2, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidIsNull() {
            addCriterion("serviceStatioinID is null");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidIsNotNull() {
            addCriterion("serviceStatioinID is not null");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidEqualTo(Integer value) {
            addCriterion("serviceStatioinID =", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidNotEqualTo(Integer value) {
            addCriterion("serviceStatioinID <>", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidGreaterThan(Integer value) {
            addCriterion("serviceStatioinID >", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidGreaterThanOrEqualTo(Integer value) {
            addCriterion("serviceStatioinID >=", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidLessThan(Integer value) {
            addCriterion("serviceStatioinID <", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidLessThanOrEqualTo(Integer value) {
            addCriterion("serviceStatioinID <=", value, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidIn(List<Integer> values) {
            addCriterion("serviceStatioinID in", values, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidNotIn(List<Integer> values) {
            addCriterion("serviceStatioinID not in", values, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidBetween(Integer value1, Integer value2) {
            addCriterion("serviceStatioinID between", value1, value2, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andServicestatioinidNotBetween(Integer value1, Integer value2) {
            addCriterion("serviceStatioinID not between", value1, value2, "servicestatioinid");
            return (Criteria) this;
        }

        public Criteria andWareidIsNull() {
            addCriterion("wareID is null");
            return (Criteria) this;
        }

        public Criteria andWareidIsNotNull() {
            addCriterion("wareID is not null");
            return (Criteria) this;
        }

        public Criteria andWareidEqualTo(Integer value) {
            addCriterion("wareID =", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotEqualTo(Integer value) {
            addCriterion("wareID <>", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThan(Integer value) {
            addCriterion("wareID >", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareID >=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThan(Integer value) {
            addCriterion("wareID <", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThanOrEqualTo(Integer value) {
            addCriterion("wareID <=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidIn(List<Integer> values) {
            addCriterion("wareID in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotIn(List<Integer> values) {
            addCriterion("wareID not in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidBetween(Integer value1, Integer value2) {
            addCriterion("wareID between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareID not between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWarepriceIsNull() {
            addCriterion("warePrice is null");
            return (Criteria) this;
        }

        public Criteria andWarepriceIsNotNull() {
            addCriterion("warePrice is not null");
            return (Criteria) this;
        }

        public Criteria andWarepriceEqualTo(BigDecimal value) {
            addCriterion("warePrice =", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceNotEqualTo(BigDecimal value) {
            addCriterion("warePrice <>", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceGreaterThan(BigDecimal value) {
            addCriterion("warePrice >", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("warePrice >=", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceLessThan(BigDecimal value) {
            addCriterion("warePrice <", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("warePrice <=", value, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceIn(List<BigDecimal> values) {
            addCriterion("warePrice in", values, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceNotIn(List<BigDecimal> values) {
            addCriterion("warePrice not in", values, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("warePrice between", value1, value2, "wareprice");
            return (Criteria) this;
        }

        public Criteria andWarepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("warePrice not between", value1, value2, "wareprice");
            return (Criteria) this;
        }

        public Criteria andMaterialidIsNull() {
            addCriterion("materialID is null");
            return (Criteria) this;
        }

        public Criteria andMaterialidIsNotNull() {
            addCriterion("materialID is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialidEqualTo(String value) {
            addCriterion("materialID =", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotEqualTo(String value) {
            addCriterion("materialID <>", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidGreaterThan(String value) {
            addCriterion("materialID >", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidGreaterThanOrEqualTo(String value) {
            addCriterion("materialID >=", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidLessThan(String value) {
            addCriterion("materialID <", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidLessThanOrEqualTo(String value) {
            addCriterion("materialID <=", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidLike(String value) {
            addCriterion("materialID like", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotLike(String value) {
            addCriterion("materialID not like", value, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidIn(List<String> values) {
            addCriterion("materialID in", values, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotIn(List<String> values) {
            addCriterion("materialID not in", values, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidBetween(String value1, String value2) {
            addCriterion("materialID between", value1, value2, "materialid");
            return (Criteria) this;
        }

        public Criteria andMaterialidNotBetween(String value1, String value2) {
            addCriterion("materialID not between", value1, value2, "materialid");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueIsNull() {
            addCriterion("CFDiscountValue is null");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueIsNotNull() {
            addCriterion("CFDiscountValue is not null");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueEqualTo(BigDecimal value) {
            addCriterion("CFDiscountValue =", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueNotEqualTo(BigDecimal value) {
            addCriterion("CFDiscountValue <>", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueGreaterThan(BigDecimal value) {
            addCriterion("CFDiscountValue >", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CFDiscountValue >=", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueLessThan(BigDecimal value) {
            addCriterion("CFDiscountValue <", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CFDiscountValue <=", value, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueIn(List<BigDecimal> values) {
            addCriterion("CFDiscountValue in", values, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueNotIn(List<BigDecimal> values) {
            addCriterion("CFDiscountValue not in", values, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CFDiscountValue between", value1, value2, "cfdiscountvalue");
            return (Criteria) this;
        }

        public Criteria andCfdiscountvalueNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CFDiscountValue not between", value1, value2, "cfdiscountvalue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table B2C_serviceStatioin_ware
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}