package com.woniu.godaji.pojo;

import java.util.Date;

public class BtcAssessWarereport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.reportID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer reportid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String warename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer townid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String townname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.reportUser
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer reportuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.reportNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer reportnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.reportDesc
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String reportdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.reportTime
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date reporttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_assess_wareReport.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.reportID
     *
     * @return the value of BTC_assess_wareReport.reportID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getReportid() {
        return reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.reportID
     *
     * @param reportid the value for BTC_assess_wareReport.reportID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReportid(Integer reportid) {
        this.reportid = reportid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.detailID
     *
     * @return the value of BTC_assess_wareReport.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.detailID
     *
     * @param detailid the value for BTC_assess_wareReport.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.wareID
     *
     * @return the value of BTC_assess_wareReport.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.wareID
     *
     * @param wareid the value for BTC_assess_wareReport.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.wareName
     *
     * @return the value of BTC_assess_wareReport.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWarename() {
        return warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.wareName
     *
     * @param warename the value for BTC_assess_wareReport.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarename(String warename) {
        this.warename = warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.storeID
     *
     * @return the value of BTC_assess_wareReport.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.storeID
     *
     * @param storeid the value for BTC_assess_wareReport.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.storeName
     *
     * @return the value of BTC_assess_wareReport.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.storeName
     *
     * @param storename the value for BTC_assess_wareReport.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorename(String storename) {
        this.storename = storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.provinceID
     *
     * @return the value of BTC_assess_wareReport.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.provinceID
     *
     * @param provinceid the value for BTC_assess_wareReport.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.provinceName
     *
     * @return the value of BTC_assess_wareReport.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.provinceName
     *
     * @param provincename the value for BTC_assess_wareReport.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.cityID
     *
     * @return the value of BTC_assess_wareReport.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.cityID
     *
     * @param cityid the value for BTC_assess_wareReport.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.cityName
     *
     * @return the value of BTC_assess_wareReport.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.cityName
     *
     * @param cityname the value for BTC_assess_wareReport.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.countyID
     *
     * @return the value of BTC_assess_wareReport.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.countyID
     *
     * @param countyid the value for BTC_assess_wareReport.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.countyName
     *
     * @return the value of BTC_assess_wareReport.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.countyName
     *
     * @param countyname the value for BTC_assess_wareReport.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.townID
     *
     * @return the value of BTC_assess_wareReport.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getTownid() {
        return townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.townID
     *
     * @param townid the value for BTC_assess_wareReport.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownid(Integer townid) {
        this.townid = townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.townName
     *
     * @return the value of BTC_assess_wareReport.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getTownname() {
        return townname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.townName
     *
     * @param townname the value for BTC_assess_wareReport.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownname(String townname) {
        this.townname = townname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.areaCode
     *
     * @return the value of BTC_assess_wareReport.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.areaCode
     *
     * @param areacode the value for BTC_assess_wareReport.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.reportUser
     *
     * @return the value of BTC_assess_wareReport.reportUser
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getReportuser() {
        return reportuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.reportUser
     *
     * @param reportuser the value for BTC_assess_wareReport.reportUser
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReportuser(Integer reportuser) {
        this.reportuser = reportuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.reportNum
     *
     * @return the value of BTC_assess_wareReport.reportNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getReportnum() {
        return reportnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.reportNum
     *
     * @param reportnum the value for BTC_assess_wareReport.reportNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReportnum(Integer reportnum) {
        this.reportnum = reportnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.reportDesc
     *
     * @return the value of BTC_assess_wareReport.reportDesc
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getReportdesc() {
        return reportdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.reportDesc
     *
     * @param reportdesc the value for BTC_assess_wareReport.reportDesc
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReportdesc(String reportdesc) {
        this.reportdesc = reportdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.reportTime
     *
     * @return the value of BTC_assess_wareReport.reportTime
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getReporttime() {
        return reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.reportTime
     *
     * @param reporttime the value for BTC_assess_wareReport.reportTime
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReporttime(Date reporttime) {
        this.reporttime = reporttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.isDelete
     *
     * @return the value of BTC_assess_wareReport.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.isDelete
     *
     * @param isdelete the value for BTC_assess_wareReport.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.isCurrent
     *
     * @return the value of BTC_assess_wareReport.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.isCurrent
     *
     * @param iscurrent the value for BTC_assess_wareReport.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.sortNum
     *
     * @return the value of BTC_assess_wareReport.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.sortNum
     *
     * @param sortnum the value for BTC_assess_wareReport.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_assess_wareReport.theNote
     *
     * @return the value of BTC_assess_wareReport.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_assess_wareReport.theNote
     *
     * @param thenote the value for BTC_assess_wareReport.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}