package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BtcDlfcsoutExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BtcDlfcsoutExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientidIsNull() {
            addCriterion("clientID is null");
            return (Criteria) this;
        }

        public Criteria andClientidIsNotNull() {
            addCriterion("clientID is not null");
            return (Criteria) this;
        }

        public Criteria andClientidEqualTo(String value) {
            addCriterion("clientID =", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotEqualTo(String value) {
            addCriterion("clientID <>", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThan(String value) {
            addCriterion("clientID >", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidGreaterThanOrEqualTo(String value) {
            addCriterion("clientID >=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThan(String value) {
            addCriterion("clientID <", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLessThanOrEqualTo(String value) {
            addCriterion("clientID <=", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidLike(String value) {
            addCriterion("clientID like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotLike(String value) {
            addCriterion("clientID not like", value, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidIn(List<String> values) {
            addCriterion("clientID in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotIn(List<String> values) {
            addCriterion("clientID not in", values, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidBetween(String value1, String value2) {
            addCriterion("clientID between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andClientidNotBetween(String value1, String value2) {
            addCriterion("clientID not between", value1, value2, "clientid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andAccountnoIsNull() {
            addCriterion("accountNo is null");
            return (Criteria) this;
        }

        public Criteria andAccountnoIsNotNull() {
            addCriterion("accountNo is not null");
            return (Criteria) this;
        }

        public Criteria andAccountnoEqualTo(String value) {
            addCriterion("accountNo =", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoNotEqualTo(String value) {
            addCriterion("accountNo <>", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoGreaterThan(String value) {
            addCriterion("accountNo >", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoGreaterThanOrEqualTo(String value) {
            addCriterion("accountNo >=", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoLessThan(String value) {
            addCriterion("accountNo <", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoLessThanOrEqualTo(String value) {
            addCriterion("accountNo <=", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoLike(String value) {
            addCriterion("accountNo like", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoNotLike(String value) {
            addCriterion("accountNo not like", value, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoIn(List<String> values) {
            addCriterion("accountNo in", values, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoNotIn(List<String> values) {
            addCriterion("accountNo not in", values, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoBetween(String value1, String value2) {
            addCriterion("accountNo between", value1, value2, "accountno");
            return (Criteria) this;
        }

        public Criteria andAccountnoNotBetween(String value1, String value2) {
            addCriterion("accountNo not between", value1, value2, "accountno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoIsNull() {
            addCriterion("recvAccNo is null");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoIsNotNull() {
            addCriterion("recvAccNo is not null");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoEqualTo(String value) {
            addCriterion("recvAccNo =", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoNotEqualTo(String value) {
            addCriterion("recvAccNo <>", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoGreaterThan(String value) {
            addCriterion("recvAccNo >", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoGreaterThanOrEqualTo(String value) {
            addCriterion("recvAccNo >=", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoLessThan(String value) {
            addCriterion("recvAccNo <", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoLessThanOrEqualTo(String value) {
            addCriterion("recvAccNo <=", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoLike(String value) {
            addCriterion("recvAccNo like", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoNotLike(String value) {
            addCriterion("recvAccNo not like", value, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoIn(List<String> values) {
            addCriterion("recvAccNo in", values, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoNotIn(List<String> values) {
            addCriterion("recvAccNo not in", values, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoBetween(String value1, String value2) {
            addCriterion("recvAccNo between", value1, value2, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnoNotBetween(String value1, String value2) {
            addCriterion("recvAccNo not between", value1, value2, "recvaccno");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmIsNull() {
            addCriterion("recvAccNm is null");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmIsNotNull() {
            addCriterion("recvAccNm is not null");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmEqualTo(String value) {
            addCriterion("recvAccNm =", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmNotEqualTo(String value) {
            addCriterion("recvAccNm <>", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmGreaterThan(String value) {
            addCriterion("recvAccNm >", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmGreaterThanOrEqualTo(String value) {
            addCriterion("recvAccNm >=", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmLessThan(String value) {
            addCriterion("recvAccNm <", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmLessThanOrEqualTo(String value) {
            addCriterion("recvAccNm <=", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmLike(String value) {
            addCriterion("recvAccNm like", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmNotLike(String value) {
            addCriterion("recvAccNm not like", value, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmIn(List<String> values) {
            addCriterion("recvAccNm in", values, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmNotIn(List<String> values) {
            addCriterion("recvAccNm not in", values, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmBetween(String value1, String value2) {
            addCriterion("recvAccNm between", value1, value2, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andRecvaccnmNotBetween(String value1, String value2) {
            addCriterion("recvAccNm not between", value1, value2, "recvaccnm");
            return (Criteria) this;
        }

        public Criteria andTranamtIsNull() {
            addCriterion("tranAmt is null");
            return (Criteria) this;
        }

        public Criteria andTranamtIsNotNull() {
            addCriterion("tranAmt is not null");
            return (Criteria) this;
        }

        public Criteria andTranamtEqualTo(BigDecimal value) {
            addCriterion("tranAmt =", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtNotEqualTo(BigDecimal value) {
            addCriterion("tranAmt <>", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtGreaterThan(BigDecimal value) {
            addCriterion("tranAmt >", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tranAmt >=", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtLessThan(BigDecimal value) {
            addCriterion("tranAmt <", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tranAmt <=", value, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtIn(List<BigDecimal> values) {
            addCriterion("tranAmt in", values, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtNotIn(List<BigDecimal> values) {
            addCriterion("tranAmt not in", values, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tranAmt between", value1, value2, "tranamt");
            return (Criteria) this;
        }

        public Criteria andTranamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tranAmt not between", value1, value2, "tranamt");
            return (Criteria) this;
        }

        public Criteria andSamebankIsNull() {
            addCriterion("sameBank is null");
            return (Criteria) this;
        }

        public Criteria andSamebankIsNotNull() {
            addCriterion("sameBank is not null");
            return (Criteria) this;
        }

        public Criteria andSamebankEqualTo(String value) {
            addCriterion("sameBank =", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankNotEqualTo(String value) {
            addCriterion("sameBank <>", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankGreaterThan(String value) {
            addCriterion("sameBank >", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankGreaterThanOrEqualTo(String value) {
            addCriterion("sameBank >=", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankLessThan(String value) {
            addCriterion("sameBank <", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankLessThanOrEqualTo(String value) {
            addCriterion("sameBank <=", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankLike(String value) {
            addCriterion("sameBank like", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankNotLike(String value) {
            addCriterion("sameBank not like", value, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankIn(List<String> values) {
            addCriterion("sameBank in", values, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankNotIn(List<String> values) {
            addCriterion("sameBank not in", values, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankBetween(String value1, String value2) {
            addCriterion("sameBank between", value1, value2, "samebank");
            return (Criteria) this;
        }

        public Criteria andSamebankNotBetween(String value1, String value2) {
            addCriterion("sameBank not between", value1, value2, "samebank");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiIsNull() {
            addCriterion("recvTgfi is null");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiIsNotNull() {
            addCriterion("recvTgfi is not null");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiEqualTo(String value) {
            addCriterion("recvTgfi =", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiNotEqualTo(String value) {
            addCriterion("recvTgfi <>", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiGreaterThan(String value) {
            addCriterion("recvTgfi >", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiGreaterThanOrEqualTo(String value) {
            addCriterion("recvTgfi >=", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiLessThan(String value) {
            addCriterion("recvTgfi <", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiLessThanOrEqualTo(String value) {
            addCriterion("recvTgfi <=", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiLike(String value) {
            addCriterion("recvTgfi like", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiNotLike(String value) {
            addCriterion("recvTgfi not like", value, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiIn(List<String> values) {
            addCriterion("recvTgfi in", values, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiNotIn(List<String> values) {
            addCriterion("recvTgfi not in", values, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiBetween(String value1, String value2) {
            addCriterion("recvTgfi between", value1, value2, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvtgfiNotBetween(String value1, String value2) {
            addCriterion("recvTgfi not between", value1, value2, "recvtgfi");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmIsNull() {
            addCriterion("recvBankNm is null");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmIsNotNull() {
            addCriterion("recvBankNm is not null");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmEqualTo(String value) {
            addCriterion("recvBankNm =", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmNotEqualTo(String value) {
            addCriterion("recvBankNm <>", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmGreaterThan(String value) {
            addCriterion("recvBankNm >", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmGreaterThanOrEqualTo(String value) {
            addCriterion("recvBankNm >=", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmLessThan(String value) {
            addCriterion("recvBankNm <", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmLessThanOrEqualTo(String value) {
            addCriterion("recvBankNm <=", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmLike(String value) {
            addCriterion("recvBankNm like", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmNotLike(String value) {
            addCriterion("recvBankNm not like", value, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmIn(List<String> values) {
            addCriterion("recvBankNm in", values, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmNotIn(List<String> values) {
            addCriterion("recvBankNm not in", values, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmBetween(String value1, String value2) {
            addCriterion("recvBankNm between", value1, value2, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andRecvbanknmNotBetween(String value1, String value2) {
            addCriterion("recvBankNm not between", value1, value2, "recvbanknm");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNull() {
            addCriterion("createDT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNotNull() {
            addCriterion("createDT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtEqualTo(Date value) {
            addCriterion("createDT =", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotEqualTo(Date value) {
            addCriterion("createDT <>", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThan(Date value) {
            addCriterion("createDT >", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThanOrEqualTo(Date value) {
            addCriterion("createDT >=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThan(Date value) {
            addCriterion("createDT <", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThanOrEqualTo(Date value) {
            addCriterion("createDT <=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtIn(List<Date> values) {
            addCriterion("createDT in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotIn(List<Date> values) {
            addCriterion("createDT not in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtBetween(Date value1, Date value2) {
            addCriterion("createDT between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotBetween(Date value1, Date value2) {
            addCriterion("createDT not between", value1, value2, "createdt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_DLFCSOUT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}