package com.woniu.godaji.pojo;

public class BtcGoodsWareWithBLOBs extends BtcGoodsWare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_goods_ware.waredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String waredetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_goods_ware.Mobilewaredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String mobilewaredetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_goods_ware.waredetail
     *
     * @return the value of BTC_goods_ware.waredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWaredetail() {
        return waredetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_goods_ware.waredetail
     *
     * @param waredetail the value for BTC_goods_ware.waredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWaredetail(String waredetail) {
        this.waredetail = waredetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_goods_ware.Mobilewaredetail
     *
     * @return the value of BTC_goods_ware.Mobilewaredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getMobilewaredetail() {
        return mobilewaredetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_goods_ware.Mobilewaredetail
     *
     * @param mobilewaredetail the value for BTC_goods_ware.Mobilewaredetail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setMobilewaredetail(String mobilewaredetail) {
        this.mobilewaredetail = mobilewaredetail;
    }
}