package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BtcGoodsWarepriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BtcGoodsWarepriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWarepriceidIsNull() {
            addCriterion("warePriceID is null");
            return (Criteria) this;
        }

        public Criteria andWarepriceidIsNotNull() {
            addCriterion("warePriceID is not null");
            return (Criteria) this;
        }

        public Criteria andWarepriceidEqualTo(Integer value) {
            addCriterion("warePriceID =", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotEqualTo(Integer value) {
            addCriterion("warePriceID <>", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidGreaterThan(Integer value) {
            addCriterion("warePriceID >", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidGreaterThanOrEqualTo(Integer value) {
            addCriterion("warePriceID >=", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidLessThan(Integer value) {
            addCriterion("warePriceID <", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidLessThanOrEqualTo(Integer value) {
            addCriterion("warePriceID <=", value, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidIn(List<Integer> values) {
            addCriterion("warePriceID in", values, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotIn(List<Integer> values) {
            addCriterion("warePriceID not in", values, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidBetween(Integer value1, Integer value2) {
            addCriterion("warePriceID between", value1, value2, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWarepriceidNotBetween(Integer value1, Integer value2) {
            addCriterion("warePriceID not between", value1, value2, "warepriceid");
            return (Criteria) this;
        }

        public Criteria andWareidIsNull() {
            addCriterion("wareID is null");
            return (Criteria) this;
        }

        public Criteria andWareidIsNotNull() {
            addCriterion("wareID is not null");
            return (Criteria) this;
        }

        public Criteria andWareidEqualTo(Integer value) {
            addCriterion("wareID =", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotEqualTo(Integer value) {
            addCriterion("wareID <>", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThan(Integer value) {
            addCriterion("wareID >", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareID >=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThan(Integer value) {
            addCriterion("wareID <", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThanOrEqualTo(Integer value) {
            addCriterion("wareID <=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidIn(List<Integer> values) {
            addCriterion("wareID in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotIn(List<Integer> values) {
            addCriterion("wareID not in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidBetween(Integer value1, Integer value2) {
            addCriterion("wareID between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareID not between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNull() {
            addCriterion("storeID is null");
            return (Criteria) this;
        }

        public Criteria andStoreidIsNotNull() {
            addCriterion("storeID is not null");
            return (Criteria) this;
        }

        public Criteria andStoreidEqualTo(Integer value) {
            addCriterion("storeID =", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotEqualTo(Integer value) {
            addCriterion("storeID <>", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThan(Integer value) {
            addCriterion("storeID >", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidGreaterThanOrEqualTo(Integer value) {
            addCriterion("storeID >=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThan(Integer value) {
            addCriterion("storeID <", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidLessThanOrEqualTo(Integer value) {
            addCriterion("storeID <=", value, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidIn(List<Integer> values) {
            addCriterion("storeID in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotIn(List<Integer> values) {
            addCriterion("storeID not in", values, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidBetween(Integer value1, Integer value2) {
            addCriterion("storeID between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoreidNotBetween(Integer value1, Integer value2) {
            addCriterion("storeID not between", value1, value2, "storeid");
            return (Criteria) this;
        }

        public Criteria andStoretagIsNull() {
            addCriterion("storeTag is null");
            return (Criteria) this;
        }

        public Criteria andStoretagIsNotNull() {
            addCriterion("storeTag is not null");
            return (Criteria) this;
        }

        public Criteria andStoretagEqualTo(String value) {
            addCriterion("storeTag =", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagNotEqualTo(String value) {
            addCriterion("storeTag <>", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagGreaterThan(String value) {
            addCriterion("storeTag >", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagGreaterThanOrEqualTo(String value) {
            addCriterion("storeTag >=", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagLessThan(String value) {
            addCriterion("storeTag <", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagLessThanOrEqualTo(String value) {
            addCriterion("storeTag <=", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagLike(String value) {
            addCriterion("storeTag like", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagNotLike(String value) {
            addCriterion("storeTag not like", value, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagIn(List<String> values) {
            addCriterion("storeTag in", values, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagNotIn(List<String> values) {
            addCriterion("storeTag not in", values, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagBetween(String value1, String value2) {
            addCriterion("storeTag between", value1, value2, "storetag");
            return (Criteria) this;
        }

        public Criteria andStoretagNotBetween(String value1, String value2) {
            addCriterion("storeTag not between", value1, value2, "storetag");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceIsNull() {
            addCriterion("padSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceIsNotNull() {
            addCriterion("padSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceEqualTo(BigDecimal value) {
            addCriterion("padSellPrice =", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceNotEqualTo(BigDecimal value) {
            addCriterion("padSellPrice <>", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceGreaterThan(BigDecimal value) {
            addCriterion("padSellPrice >", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("padSellPrice >=", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceLessThan(BigDecimal value) {
            addCriterion("padSellPrice <", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("padSellPrice <=", value, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceIn(List<BigDecimal> values) {
            addCriterion("padSellPrice in", values, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceNotIn(List<BigDecimal> values) {
            addCriterion("padSellPrice not in", values, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("padSellPrice between", value1, value2, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andPadsellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("padSellPrice not between", value1, value2, "padsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceIsNull() {
            addCriterion("wxSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceIsNotNull() {
            addCriterion("wxSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceEqualTo(BigDecimal value) {
            addCriterion("wxSellPrice =", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceNotEqualTo(BigDecimal value) {
            addCriterion("wxSellPrice <>", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceGreaterThan(BigDecimal value) {
            addCriterion("wxSellPrice >", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wxSellPrice >=", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceLessThan(BigDecimal value) {
            addCriterion("wxSellPrice <", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wxSellPrice <=", value, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceIn(List<BigDecimal> values) {
            addCriterion("wxSellPrice in", values, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceNotIn(List<BigDecimal> values) {
            addCriterion("wxSellPrice not in", values, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wxSellPrice between", value1, value2, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andWxsellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wxSellPrice not between", value1, value2, "wxsellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceIsNull() {
            addCriterion("sellPrice is null");
            return (Criteria) this;
        }

        public Criteria andSellpriceIsNotNull() {
            addCriterion("sellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andSellpriceEqualTo(BigDecimal value) {
            addCriterion("sellPrice =", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceNotEqualTo(BigDecimal value) {
            addCriterion("sellPrice <>", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceGreaterThan(BigDecimal value) {
            addCriterion("sellPrice >", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sellPrice >=", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceLessThan(BigDecimal value) {
            addCriterion("sellPrice <", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sellPrice <=", value, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceIn(List<BigDecimal> values) {
            addCriterion("sellPrice in", values, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceNotIn(List<BigDecimal> values) {
            addCriterion("sellPrice not in", values, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellPrice between", value1, value2, "sellprice");
            return (Criteria) this;
        }

        public Criteria andSellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sellPrice not between", value1, value2, "sellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceIsNull() {
            addCriterion("MobileSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceIsNotNull() {
            addCriterion("MobileSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceEqualTo(BigDecimal value) {
            addCriterion("MobileSellPrice =", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceNotEqualTo(BigDecimal value) {
            addCriterion("MobileSellPrice <>", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceGreaterThan(BigDecimal value) {
            addCriterion("MobileSellPrice >", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MobileSellPrice >=", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceLessThan(BigDecimal value) {
            addCriterion("MobileSellPrice <", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MobileSellPrice <=", value, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceIn(List<BigDecimal> values) {
            addCriterion("MobileSellPrice in", values, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceNotIn(List<BigDecimal> values) {
            addCriterion("MobileSellPrice not in", values, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MobileSellPrice between", value1, value2, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andMobilesellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MobileSellPrice not between", value1, value2, "mobilesellprice");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("Price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("Price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("Price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("Price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("Price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("Price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("Price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("Price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceIsNull() {
            addCriterion("MobileOldSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceIsNotNull() {
            addCriterion("MobileOldSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceEqualTo(BigDecimal value) {
            addCriterion("MobileOldSellPrice =", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceNotEqualTo(BigDecimal value) {
            addCriterion("MobileOldSellPrice <>", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceGreaterThan(BigDecimal value) {
            addCriterion("MobileOldSellPrice >", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MobileOldSellPrice >=", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceLessThan(BigDecimal value) {
            addCriterion("MobileOldSellPrice <", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MobileOldSellPrice <=", value, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceIn(List<BigDecimal> values) {
            addCriterion("MobileOldSellPrice in", values, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceNotIn(List<BigDecimal> values) {
            addCriterion("MobileOldSellPrice not in", values, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MobileOldSellPrice between", value1, value2, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andMobileoldsellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MobileOldSellPrice not between", value1, value2, "mobileoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceIsNull() {
            addCriterion("padOldSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceIsNotNull() {
            addCriterion("padOldSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceEqualTo(BigDecimal value) {
            addCriterion("padOldSellPrice =", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceNotEqualTo(BigDecimal value) {
            addCriterion("padOldSellPrice <>", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceGreaterThan(BigDecimal value) {
            addCriterion("padOldSellPrice >", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("padOldSellPrice >=", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceLessThan(BigDecimal value) {
            addCriterion("padOldSellPrice <", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("padOldSellPrice <=", value, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceIn(List<BigDecimal> values) {
            addCriterion("padOldSellPrice in", values, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceNotIn(List<BigDecimal> values) {
            addCriterion("padOldSellPrice not in", values, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("padOldSellPrice between", value1, value2, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andPadoldsellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("padOldSellPrice not between", value1, value2, "padoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceIsNull() {
            addCriterion("wxOldSellPrice is null");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceIsNotNull() {
            addCriterion("wxOldSellPrice is not null");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceEqualTo(BigDecimal value) {
            addCriterion("wxOldSellPrice =", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceNotEqualTo(BigDecimal value) {
            addCriterion("wxOldSellPrice <>", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceGreaterThan(BigDecimal value) {
            addCriterion("wxOldSellPrice >", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("wxOldSellPrice >=", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceLessThan(BigDecimal value) {
            addCriterion("wxOldSellPrice <", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("wxOldSellPrice <=", value, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceIn(List<BigDecimal> values) {
            addCriterion("wxOldSellPrice in", values, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceNotIn(List<BigDecimal> values) {
            addCriterion("wxOldSellPrice not in", values, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wxOldSellPrice between", value1, value2, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andWxoldsellpriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("wxOldSellPrice not between", value1, value2, "wxoldsellprice");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNull() {
            addCriterion("createDT is null");
            return (Criteria) this;
        }

        public Criteria andCreatedtIsNotNull() {
            addCriterion("createDT is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedtEqualTo(Date value) {
            addCriterion("createDT =", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotEqualTo(Date value) {
            addCriterion("createDT <>", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThan(Date value) {
            addCriterion("createDT >", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtGreaterThanOrEqualTo(Date value) {
            addCriterion("createDT >=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThan(Date value) {
            addCriterion("createDT <", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtLessThanOrEqualTo(Date value) {
            addCriterion("createDT <=", value, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtIn(List<Date> values) {
            addCriterion("createDT in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotIn(List<Date> values) {
            addCriterion("createDT not in", values, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtBetween(Date value1, Date value2) {
            addCriterion("createDT between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andCreatedtNotBetween(Date value1, Date value2) {
            addCriterion("createDT not between", value1, value2, "createdt");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNull() {
            addCriterion("isDelete is null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIsNotNull() {
            addCriterion("isDelete is not null");
            return (Criteria) this;
        }

        public Criteria andIsdeleteEqualTo(Integer value) {
            addCriterion("isDelete =", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotEqualTo(Integer value) {
            addCriterion("isDelete <>", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThan(Integer value) {
            addCriterion("isDelete >", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteGreaterThanOrEqualTo(Integer value) {
            addCriterion("isDelete >=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThan(Integer value) {
            addCriterion("isDelete <", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteLessThanOrEqualTo(Integer value) {
            addCriterion("isDelete <=", value, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteIn(List<Integer> values) {
            addCriterion("isDelete in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotIn(List<Integer> values) {
            addCriterion("isDelete not in", values, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteBetween(Integer value1, Integer value2) {
            addCriterion("isDelete between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIsdeleteNotBetween(Integer value1, Integer value2) {
            addCriterion("isDelete not between", value1, value2, "isdelete");
            return (Criteria) this;
        }

        public Criteria andIscurrentIsNull() {
            addCriterion("isCurrent is null");
            return (Criteria) this;
        }

        public Criteria andIscurrentIsNotNull() {
            addCriterion("isCurrent is not null");
            return (Criteria) this;
        }

        public Criteria andIscurrentEqualTo(Integer value) {
            addCriterion("isCurrent =", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentNotEqualTo(Integer value) {
            addCriterion("isCurrent <>", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentGreaterThan(Integer value) {
            addCriterion("isCurrent >", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentGreaterThanOrEqualTo(Integer value) {
            addCriterion("isCurrent >=", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentLessThan(Integer value) {
            addCriterion("isCurrent <", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentLessThanOrEqualTo(Integer value) {
            addCriterion("isCurrent <=", value, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentIn(List<Integer> values) {
            addCriterion("isCurrent in", values, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentNotIn(List<Integer> values) {
            addCriterion("isCurrent not in", values, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentBetween(Integer value1, Integer value2) {
            addCriterion("isCurrent between", value1, value2, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andIscurrentNotBetween(Integer value1, Integer value2) {
            addCriterion("isCurrent not between", value1, value2, "iscurrent");
            return (Criteria) this;
        }

        public Criteria andSortnumIsNull() {
            addCriterion("sortNum is null");
            return (Criteria) this;
        }

        public Criteria andSortnumIsNotNull() {
            addCriterion("sortNum is not null");
            return (Criteria) this;
        }

        public Criteria andSortnumEqualTo(Integer value) {
            addCriterion("sortNum =", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotEqualTo(Integer value) {
            addCriterion("sortNum <>", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumGreaterThan(Integer value) {
            addCriterion("sortNum >", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sortNum >=", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumLessThan(Integer value) {
            addCriterion("sortNum <", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumLessThanOrEqualTo(Integer value) {
            addCriterion("sortNum <=", value, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumIn(List<Integer> values) {
            addCriterion("sortNum in", values, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotIn(List<Integer> values) {
            addCriterion("sortNum not in", values, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumBetween(Integer value1, Integer value2) {
            addCriterion("sortNum between", value1, value2, "sortnum");
            return (Criteria) this;
        }

        public Criteria andSortnumNotBetween(Integer value1, Integer value2) {
            addCriterion("sortNum not between", value1, value2, "sortnum");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNull() {
            addCriterion("theNote is null");
            return (Criteria) this;
        }

        public Criteria andThenoteIsNotNull() {
            addCriterion("theNote is not null");
            return (Criteria) this;
        }

        public Criteria andThenoteEqualTo(String value) {
            addCriterion("theNote =", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotEqualTo(String value) {
            addCriterion("theNote <>", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThan(String value) {
            addCriterion("theNote >", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteGreaterThanOrEqualTo(String value) {
            addCriterion("theNote >=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThan(String value) {
            addCriterion("theNote <", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLessThanOrEqualTo(String value) {
            addCriterion("theNote <=", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteLike(String value) {
            addCriterion("theNote like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotLike(String value) {
            addCriterion("theNote not like", value, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteIn(List<String> values) {
            addCriterion("theNote in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotIn(List<String> values) {
            addCriterion("theNote not in", values, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteBetween(String value1, String value2) {
            addCriterion("theNote between", value1, value2, "thenote");
            return (Criteria) this;
        }

        public Criteria andThenoteNotBetween(String value1, String value2) {
            addCriterion("theNote not between", value1, value2, "thenote");
            return (Criteria) this;
        }

        public Criteria andFidIsNull() {
            addCriterion("fid is null");
            return (Criteria) this;
        }

        public Criteria andFidIsNotNull() {
            addCriterion("fid is not null");
            return (Criteria) this;
        }

        public Criteria andFidEqualTo(String value) {
            addCriterion("fid =", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotEqualTo(String value) {
            addCriterion("fid <>", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThan(String value) {
            addCriterion("fid >", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidGreaterThanOrEqualTo(String value) {
            addCriterion("fid >=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThan(String value) {
            addCriterion("fid <", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLessThanOrEqualTo(String value) {
            addCriterion("fid <=", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidLike(String value) {
            addCriterion("fid like", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotLike(String value) {
            addCriterion("fid not like", value, "fid");
            return (Criteria) this;
        }

        public Criteria andFidIn(List<String> values) {
            addCriterion("fid in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotIn(List<String> values) {
            addCriterion("fid not in", values, "fid");
            return (Criteria) this;
        }

        public Criteria andFidBetween(String value1, String value2) {
            addCriterion("fid between", value1, value2, "fid");
            return (Criteria) this;
        }

        public Criteria andFidNotBetween(String value1, String value2) {
            addCriterion("fid not between", value1, value2, "fid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}