package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BtcMarketStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storetypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storegradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.lpName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String lpname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.lpIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String lpidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.lpIDCardPhotoZ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String lpidcardphotoz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.lpIDCardPhotoF
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String lpidcardphotof;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeLogo
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storelogo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeAddress
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storeaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.positionX
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String positionx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.positionY
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String positiony;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeReturnPer
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Long storereturnper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal commissionrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storePhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeCredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal storecredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeMan
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storeman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeManPhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String storemanphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.corporationIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String corporationidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.corporationIDCardPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String corporationidcardphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.businessLicense
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String businesslicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.businessLicensePhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String businesslicensephoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.recommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date createdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.approveDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date approvedt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.dateFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer datefromsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.creator
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.storeOwnerID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storeownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.expressModeid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer expressmodeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.isWellHope
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iswellhope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.pageTitle
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String pagetitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.keywords
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.description
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.weixinAppId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String weixinappid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.weixinCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String weixincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.weixinOpenId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String weixinopenid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.accessToken
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String accesstoken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.contractSignDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date contractsigndate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.contractEndDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date contractenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.contractor
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String contractor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_store.FID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeID
     *
     * @return the value of BTC_market_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeID
     *
     * @param storeid the value for BTC_market_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeTypeID
     *
     * @return the value of BTC_market_store.storeTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoretypeid() {
        return storetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeTypeID
     *
     * @param storetypeid the value for BTC_market_store.storeTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoretypeid(Integer storetypeid) {
        this.storetypeid = storetypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeGradeID
     *
     * @return the value of BTC_market_store.storeGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoregradeid() {
        return storegradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeGradeID
     *
     * @param storegradeid the value for BTC_market_store.storeGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoregradeid(Integer storegradeid) {
        this.storegradeid = storegradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeCode
     *
     * @return the value of BTC_market_store.storeCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStorecode() {
        return storecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeCode
     *
     * @param storecode the value for BTC_market_store.storeCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorecode(String storecode) {
        this.storecode = storecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeName
     *
     * @return the value of BTC_market_store.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStorename() {
        return storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeName
     *
     * @param storename the value for BTC_market_store.storeName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorename(String storename) {
        this.storename = storename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.lpName
     *
     * @return the value of BTC_market_store.lpName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLpname() {
        return lpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.lpName
     *
     * @param lpname the value for BTC_market_store.lpName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLpname(String lpname) {
        this.lpname = lpname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.lpIDCard
     *
     * @return the value of BTC_market_store.lpIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLpidcard() {
        return lpidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.lpIDCard
     *
     * @param lpidcard the value for BTC_market_store.lpIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLpidcard(String lpidcard) {
        this.lpidcard = lpidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.lpIDCardPhotoZ
     *
     * @return the value of BTC_market_store.lpIDCardPhotoZ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLpidcardphotoz() {
        return lpidcardphotoz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.lpIDCardPhotoZ
     *
     * @param lpidcardphotoz the value for BTC_market_store.lpIDCardPhotoZ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLpidcardphotoz(String lpidcardphotoz) {
        this.lpidcardphotoz = lpidcardphotoz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.lpIDCardPhotoF
     *
     * @return the value of BTC_market_store.lpIDCardPhotoF
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLpidcardphotof() {
        return lpidcardphotof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.lpIDCardPhotoF
     *
     * @param lpidcardphotof the value for BTC_market_store.lpIDCardPhotoF
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLpidcardphotof(String lpidcardphotof) {
        this.lpidcardphotof = lpidcardphotof;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.provinceID
     *
     * @return the value of BTC_market_store.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.provinceID
     *
     * @param provinceid the value for BTC_market_store.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.provinceName
     *
     * @return the value of BTC_market_store.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.provinceName
     *
     * @param provincename the value for BTC_market_store.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.cityID
     *
     * @return the value of BTC_market_store.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.cityID
     *
     * @param cityid the value for BTC_market_store.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.cityName
     *
     * @return the value of BTC_market_store.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.cityName
     *
     * @param cityname the value for BTC_market_store.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.countyID
     *
     * @return the value of BTC_market_store.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.countyID
     *
     * @param countyid the value for BTC_market_store.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.countyName
     *
     * @return the value of BTC_market_store.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.countyName
     *
     * @param countyname the value for BTC_market_store.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeLogo
     *
     * @return the value of BTC_market_store.storeLogo
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStorelogo() {
        return storelogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeLogo
     *
     * @param storelogo the value for BTC_market_store.storeLogo
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorelogo(String storelogo) {
        this.storelogo = storelogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeAddress
     *
     * @return the value of BTC_market_store.storeAddress
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStoreaddress() {
        return storeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeAddress
     *
     * @param storeaddress the value for BTC_market_store.storeAddress
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreaddress(String storeaddress) {
        this.storeaddress = storeaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.positionX
     *
     * @return the value of BTC_market_store.positionX
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getPositionx() {
        return positionx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.positionX
     *
     * @param positionx the value for BTC_market_store.positionX
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPositionx(String positionx) {
        this.positionx = positionx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.positionY
     *
     * @return the value of BTC_market_store.positionY
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getPositiony() {
        return positiony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.positionY
     *
     * @param positiony the value for BTC_market_store.positionY
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPositiony(String positiony) {
        this.positiony = positiony;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeReturnPer
     *
     * @return the value of BTC_market_store.storeReturnPer
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Long getStorereturnper() {
        return storereturnper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeReturnPer
     *
     * @param storereturnper the value for BTC_market_store.storeReturnPer
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorereturnper(Long storereturnper) {
        this.storereturnper = storereturnper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.CommissionRate
     *
     * @return the value of BTC_market_store.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCommissionrate() {
        return commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.CommissionRate
     *
     * @param commissionrate the value for BTC_market_store.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCommissionrate(BigDecimal commissionrate) {
        this.commissionrate = commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storePhone
     *
     * @return the value of BTC_market_store.storePhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStorephone() {
        return storephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storePhone
     *
     * @param storephone the value for BTC_market_store.storePhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorephone(String storephone) {
        this.storephone = storephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeCredit
     *
     * @return the value of BTC_market_store.storeCredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getStorecredit() {
        return storecredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeCredit
     *
     * @param storecredit the value for BTC_market_store.storeCredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStorecredit(BigDecimal storecredit) {
        this.storecredit = storecredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeMan
     *
     * @return the value of BTC_market_store.storeMan
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStoreman() {
        return storeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeMan
     *
     * @param storeman the value for BTC_market_store.storeMan
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreman(String storeman) {
        this.storeman = storeman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeManPhone
     *
     * @return the value of BTC_market_store.storeManPhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getStoremanphone() {
        return storemanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeManPhone
     *
     * @param storemanphone the value for BTC_market_store.storeManPhone
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoremanphone(String storemanphone) {
        this.storemanphone = storemanphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.corporationIDCard
     *
     * @return the value of BTC_market_store.corporationIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCorporationidcard() {
        return corporationidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.corporationIDCard
     *
     * @param corporationidcard the value for BTC_market_store.corporationIDCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCorporationidcard(String corporationidcard) {
        this.corporationidcard = corporationidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.corporationIDCardPhoto
     *
     * @return the value of BTC_market_store.corporationIDCardPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCorporationidcardphoto() {
        return corporationidcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.corporationIDCardPhoto
     *
     * @param corporationidcardphoto the value for BTC_market_store.corporationIDCardPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCorporationidcardphoto(String corporationidcardphoto) {
        this.corporationidcardphoto = corporationidcardphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.businessLicense
     *
     * @return the value of BTC_market_store.businessLicense
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBusinesslicense() {
        return businesslicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.businessLicense
     *
     * @param businesslicense the value for BTC_market_store.businessLicense
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.businessLicensePhoto
     *
     * @return the value of BTC_market_store.businessLicensePhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBusinesslicensephoto() {
        return businesslicensephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.businessLicensePhoto
     *
     * @param businesslicensephoto the value for BTC_market_store.businessLicensePhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBusinesslicensephoto(String businesslicensephoto) {
        this.businesslicensephoto = businesslicensephoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.infoType
     *
     * @return the value of BTC_market_store.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.infoType
     *
     * @param infotype the value for BTC_market_store.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setInfotype(Integer infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.recommend
     *
     * @return the value of BTC_market_store.recommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.recommend
     *
     * @param recommend the value for BTC_market_store.recommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.createDT
     *
     * @return the value of BTC_market_store.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.createDT
     *
     * @param createdt the value for BTC_market_store.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.approveDT
     *
     * @return the value of BTC_market_store.approveDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getApprovedt() {
        return approvedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.approveDT
     *
     * @param approvedt the value for BTC_market_store.approveDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setApprovedt(Date approvedt) {
        this.approvedt = approvedt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.dateFromSource
     *
     * @return the value of BTC_market_store.dateFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getDatefromsource() {
        return datefromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.dateFromSource
     *
     * @param datefromsource the value for BTC_market_store.dateFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDatefromsource(Integer datefromsource) {
        this.datefromsource = datefromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.creator
     *
     * @return the value of BTC_market_store.creator
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.creator
     *
     * @param creator the value for BTC_market_store.creator
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.isDelete
     *
     * @return the value of BTC_market_store.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.isDelete
     *
     * @param isdelete the value for BTC_market_store.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.storeOwnerID
     *
     * @return the value of BTC_market_store.storeOwnerID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoreownerid() {
        return storeownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.storeOwnerID
     *
     * @param storeownerid the value for BTC_market_store.storeOwnerID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreownerid(Integer storeownerid) {
        this.storeownerid = storeownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.expressModeid
     *
     * @return the value of BTC_market_store.expressModeid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getExpressmodeid() {
        return expressmodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.expressModeid
     *
     * @param expressmodeid the value for BTC_market_store.expressModeid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setExpressmodeid(Integer expressmodeid) {
        this.expressmodeid = expressmodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.isWellHope
     *
     * @return the value of BTC_market_store.isWellHope
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIswellhope() {
        return iswellhope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.isWellHope
     *
     * @param iswellhope the value for BTC_market_store.isWellHope
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIswellhope(Integer iswellhope) {
        this.iswellhope = iswellhope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.isCurrent
     *
     * @return the value of BTC_market_store.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.isCurrent
     *
     * @param iscurrent the value for BTC_market_store.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.sortNum
     *
     * @return the value of BTC_market_store.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.sortNum
     *
     * @param sortnum the value for BTC_market_store.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.theNote
     *
     * @return the value of BTC_market_store.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.theNote
     *
     * @param thenote the value for BTC_market_store.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.pageTitle
     *
     * @return the value of BTC_market_store.pageTitle
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getPagetitle() {
        return pagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.pageTitle
     *
     * @param pagetitle the value for BTC_market_store.pageTitle
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPagetitle(String pagetitle) {
        this.pagetitle = pagetitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.keywords
     *
     * @return the value of BTC_market_store.keywords
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.keywords
     *
     * @param keywords the value for BTC_market_store.keywords
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.description
     *
     * @return the value of BTC_market_store.description
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.description
     *
     * @param description the value for BTC_market_store.description
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.weixinAppId
     *
     * @return the value of BTC_market_store.weixinAppId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWeixinappid() {
        return weixinappid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.weixinAppId
     *
     * @param weixinappid the value for BTC_market_store.weixinAppId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWeixinappid(String weixinappid) {
        this.weixinappid = weixinappid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.weixinCode
     *
     * @return the value of BTC_market_store.weixinCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWeixincode() {
        return weixincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.weixinCode
     *
     * @param weixincode the value for BTC_market_store.weixinCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWeixincode(String weixincode) {
        this.weixincode = weixincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.weixinOpenId
     *
     * @return the value of BTC_market_store.weixinOpenId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWeixinopenid() {
        return weixinopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.weixinOpenId
     *
     * @param weixinopenid the value for BTC_market_store.weixinOpenId
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWeixinopenid(String weixinopenid) {
        this.weixinopenid = weixinopenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.accessToken
     *
     * @return the value of BTC_market_store.accessToken
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.accessToken
     *
     * @param accesstoken the value for BTC_market_store.accessToken
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.contractSignDate
     *
     * @return the value of BTC_market_store.contractSignDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getContractsigndate() {
        return contractsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.contractSignDate
     *
     * @param contractsigndate the value for BTC_market_store.contractSignDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setContractsigndate(Date contractsigndate) {
        this.contractsigndate = contractsigndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.contractEndDate
     *
     * @return the value of BTC_market_store.contractEndDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getContractenddate() {
        return contractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.contractEndDate
     *
     * @param contractenddate the value for BTC_market_store.contractEndDate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setContractenddate(Date contractenddate) {
        this.contractenddate = contractenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.contractor
     *
     * @return the value of BTC_market_store.contractor
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getContractor() {
        return contractor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.contractor
     *
     * @param contractor the value for BTC_market_store.contractor
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setContractor(String contractor) {
        this.contractor = contractor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_store.FID
     *
     * @return the value of BTC_market_store.FID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_store.FID
     *
     * @param fid the value for BTC_market_store.FID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setFid(String fid) {
        this.fid = fid;
    }
}