package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BtcMarketOrderdetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer detailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer forderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.sorderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String warecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String wareno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String warename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal warecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.inPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal inprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal wareprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String wareunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareWeightUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String wareweightunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.priceCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal pricecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.couponCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal couponcash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal reducecash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer warepriceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.wareAttribute
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String wareattribute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.returnCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal returncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal returncash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal commissionrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date createdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.buyQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer buyqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.GiveQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer giveqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.buyCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal buycash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.reduceCash2
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal reducecash2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_market_orderDetail.listImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String listimg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.detailID
     *
     * @return the value of BTC_market_orderDetail.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getDetailid() {
        return detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.detailID
     *
     * @param detailid the value for BTC_market_orderDetail.detailID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDetailid(Integer detailid) {
        this.detailid = detailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.forderID
     *
     * @return the value of BTC_market_orderDetail.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getForderid() {
        return forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.forderID
     *
     * @param forderid the value for BTC_market_orderDetail.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setForderid(Integer forderid) {
        this.forderid = forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.sorderID
     *
     * @return the value of BTC_market_orderDetail.sorderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSorderid() {
        return sorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.sorderID
     *
     * @param sorderid the value for BTC_market_orderDetail.sorderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSorderid(Integer sorderid) {
        this.sorderid = sorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.userID
     *
     * @return the value of BTC_market_orderDetail.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.userID
     *
     * @param userid the value for BTC_market_orderDetail.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.storeID
     *
     * @return the value of BTC_market_orderDetail.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.storeID
     *
     * @param storeid the value for BTC_market_orderDetail.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareID
     *
     * @return the value of BTC_market_orderDetail.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareID
     *
     * @param wareid the value for BTC_market_orderDetail.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareCode
     *
     * @return the value of BTC_market_orderDetail.wareCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWarecode() {
        return warecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareCode
     *
     * @param warecode the value for BTC_market_orderDetail.wareCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarecode(String warecode) {
        this.warecode = warecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareNO
     *
     * @return the value of BTC_market_orderDetail.wareNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWareno() {
        return wareno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareNO
     *
     * @param wareno the value for BTC_market_orderDetail.wareNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareno(String wareno) {
        this.wareno = wareno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareName
     *
     * @return the value of BTC_market_orderDetail.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWarename() {
        return warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareName
     *
     * @param warename the value for BTC_market_orderDetail.wareName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarename(String warename) {
        this.warename = warename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareCount
     *
     * @return the value of BTC_market_orderDetail.wareCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getWarecount() {
        return warecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareCount
     *
     * @param warecount the value for BTC_market_orderDetail.wareCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarecount(BigDecimal warecount) {
        this.warecount = warecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.inPrice
     *
     * @return the value of BTC_market_orderDetail.inPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getInprice() {
        return inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.inPrice
     *
     * @param inprice the value for BTC_market_orderDetail.inPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setInprice(BigDecimal inprice) {
        this.inprice = inprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.warePrice
     *
     * @return the value of BTC_market_orderDetail.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getWareprice() {
        return wareprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.warePrice
     *
     * @param wareprice the value for BTC_market_orderDetail.warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareprice(BigDecimal wareprice) {
        this.wareprice = wareprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareUnit
     *
     * @return the value of BTC_market_orderDetail.wareUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWareunit() {
        return wareunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareUnit
     *
     * @param wareunit the value for BTC_market_orderDetail.wareUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareunit(String wareunit) {
        this.wareunit = wareunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareWeightUnit
     *
     * @return the value of BTC_market_orderDetail.wareWeightUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWareweightunit() {
        return wareweightunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareWeightUnit
     *
     * @param wareweightunit the value for BTC_market_orderDetail.wareWeightUnit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareweightunit(String wareweightunit) {
        this.wareweightunit = wareweightunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.priceCount
     *
     * @return the value of BTC_market_orderDetail.priceCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getPricecount() {
        return pricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.priceCount
     *
     * @param pricecount the value for BTC_market_orderDetail.priceCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPricecount(BigDecimal pricecount) {
        this.pricecount = pricecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.couponCash
     *
     * @return the value of BTC_market_orderDetail.couponCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCouponcash() {
        return couponcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.couponCash
     *
     * @param couponcash the value for BTC_market_orderDetail.couponCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCouponcash(BigDecimal couponcash) {
        this.couponcash = couponcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.reduceCash
     *
     * @return the value of BTC_market_orderDetail.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReducecash() {
        return reducecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.reduceCash
     *
     * @param reducecash the value for BTC_market_orderDetail.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReducecash(BigDecimal reducecash) {
        this.reducecash = reducecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.warePriceID
     *
     * @return the value of BTC_market_orderDetail.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWarepriceid() {
        return warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.warePriceID
     *
     * @param warepriceid the value for BTC_market_orderDetail.warePriceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarepriceid(Integer warepriceid) {
        this.warepriceid = warepriceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.wareAttribute
     *
     * @return the value of BTC_market_orderDetail.wareAttribute
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWareattribute() {
        return wareattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.wareAttribute
     *
     * @param wareattribute the value for BTC_market_orderDetail.wareAttribute
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareattribute(String wareattribute) {
        this.wareattribute = wareattribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.returnCount
     *
     * @return the value of BTC_market_orderDetail.returnCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReturncount() {
        return returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.returnCount
     *
     * @param returncount the value for BTC_market_orderDetail.returnCount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReturncount(BigDecimal returncount) {
        this.returncount = returncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.returnCash
     *
     * @return the value of BTC_market_orderDetail.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReturncash() {
        return returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.returnCash
     *
     * @param returncash the value for BTC_market_orderDetail.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReturncash(BigDecimal returncash) {
        this.returncash = returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.CommissionRate
     *
     * @return the value of BTC_market_orderDetail.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCommissionrate() {
        return commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.CommissionRate
     *
     * @param commissionrate the value for BTC_market_orderDetail.CommissionRate
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCommissionrate(BigDecimal commissionrate) {
        this.commissionrate = commissionrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.createDT
     *
     * @return the value of BTC_market_orderDetail.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.createDT
     *
     * @param createdt the value for BTC_market_orderDetail.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.buyQty
     *
     * @return the value of BTC_market_orderDetail.buyQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getBuyqty() {
        return buyqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.buyQty
     *
     * @param buyqty the value for BTC_market_orderDetail.buyQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBuyqty(Integer buyqty) {
        this.buyqty = buyqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.GiveQty
     *
     * @return the value of BTC_market_orderDetail.GiveQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getGiveqty() {
        return giveqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.GiveQty
     *
     * @param giveqty the value for BTC_market_orderDetail.GiveQty
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setGiveqty(Integer giveqty) {
        this.giveqty = giveqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.buyCash
     *
     * @return the value of BTC_market_orderDetail.buyCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getBuycash() {
        return buycash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.buyCash
     *
     * @param buycash the value for BTC_market_orderDetail.buyCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBuycash(BigDecimal buycash) {
        this.buycash = buycash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.reduceCash2
     *
     * @return the value of BTC_market_orderDetail.reduceCash2
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReducecash2() {
        return reducecash2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.reduceCash2
     *
     * @param reducecash2 the value for BTC_market_orderDetail.reduceCash2
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReducecash2(BigDecimal reducecash2) {
        this.reducecash2 = reducecash2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.isDelete
     *
     * @return the value of BTC_market_orderDetail.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.isDelete
     *
     * @param isdelete the value for BTC_market_orderDetail.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.isCurrent
     *
     * @return the value of BTC_market_orderDetail.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.isCurrent
     *
     * @param iscurrent the value for BTC_market_orderDetail.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.sortNum
     *
     * @return the value of BTC_market_orderDetail.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.sortNum
     *
     * @param sortnum the value for BTC_market_orderDetail.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.theNote
     *
     * @return the value of BTC_market_orderDetail.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.theNote
     *
     * @param thenote the value for BTC_market_orderDetail.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_market_orderDetail.listImg
     *
     * @return the value of BTC_market_orderDetail.listImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getListimg() {
        return listimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_market_orderDetail.listImg
     *
     * @param listimg the value for BTC_market_orderDetail.listImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setListimg(String listimg) {
        this.listimg = listimg;
    }
}