package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class BtcPreferentialDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BtcPreferentialDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBtcPdidIsNull() {
            addCriterion("btc_pdID is null");
            return (Criteria) this;
        }

        public Criteria andBtcPdidIsNotNull() {
            addCriterion("btc_pdID is not null");
            return (Criteria) this;
        }

        public Criteria andBtcPdidEqualTo(Integer value) {
            addCriterion("btc_pdID =", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidNotEqualTo(Integer value) {
            addCriterion("btc_pdID <>", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidGreaterThan(Integer value) {
            addCriterion("btc_pdID >", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidGreaterThanOrEqualTo(Integer value) {
            addCriterion("btc_pdID >=", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidLessThan(Integer value) {
            addCriterion("btc_pdID <", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidLessThanOrEqualTo(Integer value) {
            addCriterion("btc_pdID <=", value, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidIn(List<Integer> values) {
            addCriterion("btc_pdID in", values, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidNotIn(List<Integer> values) {
            addCriterion("btc_pdID not in", values, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidBetween(Integer value1, Integer value2) {
            addCriterion("btc_pdID between", value1, value2, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPdidNotBetween(Integer value1, Integer value2) {
            addCriterion("btc_pdID not between", value1, value2, "btcPdid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidIsNull() {
            addCriterion("btc_ppID is null");
            return (Criteria) this;
        }

        public Criteria andBtcPpidIsNotNull() {
            addCriterion("btc_ppID is not null");
            return (Criteria) this;
        }

        public Criteria andBtcPpidEqualTo(Integer value) {
            addCriterion("btc_ppID =", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidNotEqualTo(Integer value) {
            addCriterion("btc_ppID <>", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidGreaterThan(Integer value) {
            addCriterion("btc_ppID >", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidGreaterThanOrEqualTo(Integer value) {
            addCriterion("btc_ppID >=", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidLessThan(Integer value) {
            addCriterion("btc_ppID <", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidLessThanOrEqualTo(Integer value) {
            addCriterion("btc_ppID <=", value, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidIn(List<Integer> values) {
            addCriterion("btc_ppID in", values, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidNotIn(List<Integer> values) {
            addCriterion("btc_ppID not in", values, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidBetween(Integer value1, Integer value2) {
            addCriterion("btc_ppID between", value1, value2, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andBtcPpidNotBetween(Integer value1, Integer value2) {
            addCriterion("btc_ppID not between", value1, value2, "btcPpid");
            return (Criteria) this;
        }

        public Criteria andWareidIsNull() {
            addCriterion("wareID is null");
            return (Criteria) this;
        }

        public Criteria andWareidIsNotNull() {
            addCriterion("wareID is not null");
            return (Criteria) this;
        }

        public Criteria andWareidEqualTo(Integer value) {
            addCriterion("wareID =", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotEqualTo(Integer value) {
            addCriterion("wareID <>", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThan(Integer value) {
            addCriterion("wareID >", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareID >=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThan(Integer value) {
            addCriterion("wareID <", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidLessThanOrEqualTo(Integer value) {
            addCriterion("wareID <=", value, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidIn(List<Integer> values) {
            addCriterion("wareID in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotIn(List<Integer> values) {
            addCriterion("wareID not in", values, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidBetween(Integer value1, Integer value2) {
            addCriterion("wareID between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andWareidNotBetween(Integer value1, Integer value2) {
            addCriterion("wareID not between", value1, value2, "wareid");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNull() {
            addCriterion("salePrice is null");
            return (Criteria) this;
        }

        public Criteria andSalepriceIsNotNull() {
            addCriterion("salePrice is not null");
            return (Criteria) this;
        }

        public Criteria andSalepriceEqualTo(BigDecimal value) {
            addCriterion("salePrice =", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotEqualTo(BigDecimal value) {
            addCriterion("salePrice <>", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThan(BigDecimal value) {
            addCriterion("salePrice >", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice >=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThan(BigDecimal value) {
            addCriterion("salePrice <", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("salePrice <=", value, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceIn(List<BigDecimal> values) {
            addCriterion("salePrice in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotIn(List<BigDecimal> values) {
            addCriterion("salePrice not in", values, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andSalepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("salePrice not between", value1, value2, "saleprice");
            return (Criteria) this;
        }

        public Criteria andWareqtyIsNull() {
            addCriterion("wareQty is null");
            return (Criteria) this;
        }

        public Criteria andWareqtyIsNotNull() {
            addCriterion("wareQty is not null");
            return (Criteria) this;
        }

        public Criteria andWareqtyEqualTo(Integer value) {
            addCriterion("wareQty =", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyNotEqualTo(Integer value) {
            addCriterion("wareQty <>", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyGreaterThan(Integer value) {
            addCriterion("wareQty >", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("wareQty >=", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyLessThan(Integer value) {
            addCriterion("wareQty <", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyLessThanOrEqualTo(Integer value) {
            addCriterion("wareQty <=", value, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyIn(List<Integer> values) {
            addCriterion("wareQty in", values, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyNotIn(List<Integer> values) {
            addCriterion("wareQty not in", values, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyBetween(Integer value1, Integer value2) {
            addCriterion("wareQty between", value1, value2, "wareqty");
            return (Criteria) this;
        }

        public Criteria andWareqtyNotBetween(Integer value1, Integer value2) {
            addCriterion("wareQty not between", value1, value2, "wareqty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table btc_Preferential_detail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}