package com.woniu.godaji.pojo;

public class BtcSysWareactivitywt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareActivityWT.wareActivityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareactivityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareActivityWT.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareclassificationtypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareActivityWT.wareActivityID
     *
     * @return the value of BTC_sys_wareActivityWT.wareActivityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareactivityid() {
        return wareactivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareActivityWT.wareActivityID
     *
     * @param wareactivityid the value for BTC_sys_wareActivityWT.wareActivityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareactivityid(Integer wareactivityid) {
        this.wareactivityid = wareactivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareActivityWT.wareClassificationTypeID
     *
     * @return the value of BTC_sys_wareActivityWT.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareclassificationtypeid() {
        return wareclassificationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareActivityWT.wareClassificationTypeID
     *
     * @param wareclassificationtypeid the value for BTC_sys_wareActivityWT.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareclassificationtypeid(Integer wareclassificationtypeid) {
        this.wareclassificationtypeid = wareclassificationtypeid;
    }
}