package com.woniu.godaji.pojo;

public class BtcSysWarespec {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.wareSpecID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer warespecid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.wareSpec
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String warespec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareSpec.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.wareSpecID
     *
     * @return the value of BTC_sys_wareSpec.wareSpecID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWarespecid() {
        return warespecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.wareSpecID
     *
     * @param warespecid the value for BTC_sys_wareSpec.wareSpecID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarespecid(Integer warespecid) {
        this.warespecid = warespecid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.wareSpec
     *
     * @return the value of BTC_sys_wareSpec.wareSpec
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getWarespec() {
        return warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.wareSpec
     *
     * @param warespec the value for BTC_sys_wareSpec.wareSpec
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarespec(String warespec) {
        this.warespec = warespec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.isDelete
     *
     * @return the value of BTC_sys_wareSpec.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.isDelete
     *
     * @param isdelete the value for BTC_sys_wareSpec.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.isCurrent
     *
     * @return the value of BTC_sys_wareSpec.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.isCurrent
     *
     * @param iscurrent the value for BTC_sys_wareSpec.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.sortNum
     *
     * @return the value of BTC_sys_wareSpec.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.sortNum
     *
     * @param sortnum the value for BTC_sys_wareSpec.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareSpec.theNote
     *
     * @return the value of BTC_sys_wareSpec.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareSpec.theNote
     *
     * @param thenote the value for BTC_sys_wareSpec.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}