package com.woniu.godaji.pojo;

public class BtcSysWarecftbrand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareCftBrand.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareclassificationtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_sys_wareCftBrand.wareBrandID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer warebrandid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareCftBrand.wareClassificationTypeID
     *
     * @return the value of BTC_sys_wareCftBrand.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareclassificationtypeid() {
        return wareclassificationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareCftBrand.wareClassificationTypeID
     *
     * @param wareclassificationtypeid the value for BTC_sys_wareCftBrand.wareClassificationTypeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareclassificationtypeid(Integer wareclassificationtypeid) {
        this.wareclassificationtypeid = wareclassificationtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_sys_wareCftBrand.wareBrandID
     *
     * @return the value of BTC_sys_wareCftBrand.wareBrandID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWarebrandid() {
        return warebrandid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_sys_wareCftBrand.wareBrandID
     *
     * @param warebrandid the value for BTC_sys_wareCftBrand.wareBrandID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWarebrandid(Integer warebrandid) {
        this.warebrandid = warebrandid;
    }
}