package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class BtcUserForder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer forderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.forderCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String fordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date createdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.forderPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal forderprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.payMoney
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal returncash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.usercouponID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer usercouponid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.couponCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String couponcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.couponCodeValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal couponcodevalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal reducecash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.express
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal express;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.billno
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String billno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.payState
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer paystate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.paytype
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.payDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date paydt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.serviceStatioinName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String servicestatioinname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.orderFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer orderfromsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.ip
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.autoCancelDays
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer autocanceldays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.fromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer fromsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_forder.receiptAddrID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer receiptaddrid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.forderID
     *
     * @return the value of BTC_user_forder.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getForderid() {
        return forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.forderID
     *
     * @param forderid the value for BTC_user_forder.forderID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setForderid(Integer forderid) {
        this.forderid = forderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.forderCode
     *
     * @return the value of BTC_user_forder.forderCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getFordercode() {
        return fordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.forderCode
     *
     * @param fordercode the value for BTC_user_forder.forderCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setFordercode(String fordercode) {
        this.fordercode = fordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.userID
     *
     * @return the value of BTC_user_forder.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.userID
     *
     * @param userid the value for BTC_user_forder.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.createDT
     *
     * @return the value of BTC_user_forder.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getCreatedt() {
        return createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.createDT
     *
     * @param createdt the value for BTC_user_forder.createDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCreatedt(Date createdt) {
        this.createdt = createdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.forderPrice
     *
     * @return the value of BTC_user_forder.forderPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getForderprice() {
        return forderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.forderPrice
     *
     * @param forderprice the value for BTC_user_forder.forderPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setForderprice(BigDecimal forderprice) {
        this.forderprice = forderprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.payMoney
     *
     * @return the value of BTC_user_forder.payMoney
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.payMoney
     *
     * @param paymoney the value for BTC_user_forder.payMoney
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.returnCash
     *
     * @return the value of BTC_user_forder.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReturncash() {
        return returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.returnCash
     *
     * @param returncash the value for BTC_user_forder.returnCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReturncash(BigDecimal returncash) {
        this.returncash = returncash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.usercouponID
     *
     * @return the value of BTC_user_forder.usercouponID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUsercouponid() {
        return usercouponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.usercouponID
     *
     * @param usercouponid the value for BTC_user_forder.usercouponID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsercouponid(Integer usercouponid) {
        this.usercouponid = usercouponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.couponCode
     *
     * @return the value of BTC_user_forder.couponCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCouponcode() {
        return couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.couponCode
     *
     * @param couponcode the value for BTC_user_forder.couponCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCouponcode(String couponcode) {
        this.couponcode = couponcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.couponCodeValue
     *
     * @return the value of BTC_user_forder.couponCodeValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCouponcodevalue() {
        return couponcodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.couponCodeValue
     *
     * @param couponcodevalue the value for BTC_user_forder.couponCodeValue
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCouponcodevalue(BigDecimal couponcodevalue) {
        this.couponcodevalue = couponcodevalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.reduceCash
     *
     * @return the value of BTC_user_forder.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getReducecash() {
        return reducecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.reduceCash
     *
     * @param reducecash the value for BTC_user_forder.reduceCash
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReducecash(BigDecimal reducecash) {
        this.reducecash = reducecash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.express
     *
     * @return the value of BTC_user_forder.express
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getExpress() {
        return express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.express
     *
     * @param express the value for BTC_user_forder.express
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setExpress(BigDecimal express) {
        this.express = express;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.billno
     *
     * @return the value of BTC_user_forder.billno
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.billno
     *
     * @param billno the value for BTC_user_forder.billno
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBillno(String billno) {
        this.billno = billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.payState
     *
     * @return the value of BTC_user_forder.payState
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getPaystate() {
        return paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.payState
     *
     * @param paystate the value for BTC_user_forder.payState
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPaystate(Integer paystate) {
        this.paystate = paystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.paytype
     *
     * @return the value of BTC_user_forder.paytype
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.paytype
     *
     * @param paytype the value for BTC_user_forder.paytype
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPaytype(Integer paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.payDT
     *
     * @return the value of BTC_user_forder.payDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getPaydt() {
        return paydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.payDT
     *
     * @param paydt the value for BTC_user_forder.payDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPaydt(Date paydt) {
        this.paydt = paydt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.serviceStatioinName
     *
     * @return the value of BTC_user_forder.serviceStatioinName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getServicestatioinname() {
        return servicestatioinname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.serviceStatioinName
     *
     * @param servicestatioinname the value for BTC_user_forder.serviceStatioinName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setServicestatioinname(String servicestatioinname) {
        this.servicestatioinname = servicestatioinname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.orderFromSource
     *
     * @return the value of BTC_user_forder.orderFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getOrderfromsource() {
        return orderfromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.orderFromSource
     *
     * @param orderfromsource the value for BTC_user_forder.orderFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setOrderfromsource(Integer orderfromsource) {
        this.orderfromsource = orderfromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.ip
     *
     * @return the value of BTC_user_forder.ip
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.ip
     *
     * @param ip the value for BTC_user_forder.ip
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.autoCancelDays
     *
     * @return the value of BTC_user_forder.autoCancelDays
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getAutocanceldays() {
        return autocanceldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.autoCancelDays
     *
     * @param autocanceldays the value for BTC_user_forder.autoCancelDays
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setAutocanceldays(Integer autocanceldays) {
        this.autocanceldays = autocanceldays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.isDelete
     *
     * @return the value of BTC_user_forder.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.isDelete
     *
     * @param isdelete the value for BTC_user_forder.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.sortNum
     *
     * @return the value of BTC_user_forder.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.sortNum
     *
     * @param sortnum the value for BTC_user_forder.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.theNote
     *
     * @return the value of BTC_user_forder.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.theNote
     *
     * @param thenote the value for BTC_user_forder.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.fromSource
     *
     * @return the value of BTC_user_forder.fromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getFromsource() {
        return fromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.fromSource
     *
     * @param fromsource the value for BTC_user_forder.fromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setFromsource(Integer fromsource) {
        this.fromsource = fromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_forder.receiptAddrID
     *
     * @return the value of BTC_user_forder.receiptAddrID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getReceiptaddrid() {
        return receiptaddrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_forder.receiptAddrID
     *
     * @param receiptaddrid the value for BTC_user_forder.receiptAddrID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setReceiptaddrid(Integer receiptaddrid) {
        this.receiptaddrid = receiptaddrid;
    }
}