package com.woniu.godaji.pojo;

import java.math.BigDecimal;

public class BtcUserUsercredit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.creditID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer creditid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.credit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer townid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BTC_user_userCredit.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String townname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.creditID
     *
     * @return the value of BTC_user_userCredit.creditID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCreditid() {
        return creditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.creditID
     *
     * @param creditid the value for BTC_user_userCredit.creditID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCreditid(Integer creditid) {
        this.creditid = creditid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.userID
     *
     * @return the value of BTC_user_userCredit.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.userID
     *
     * @param userid the value for BTC_user_userCredit.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.loginName
     *
     * @return the value of BTC_user_userCredit.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.loginName
     *
     * @param loginname the value for BTC_user_userCredit.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.credit
     *
     * @return the value of BTC_user_userCredit.credit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.credit
     *
     * @param credit the value for BTC_user_userCredit.credit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.isDelete
     *
     * @return the value of BTC_user_userCredit.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.isDelete
     *
     * @param isdelete the value for BTC_user_userCredit.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.isCurrent
     *
     * @return the value of BTC_user_userCredit.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.isCurrent
     *
     * @param iscurrent the value for BTC_user_userCredit.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.sortNum
     *
     * @return the value of BTC_user_userCredit.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.sortNum
     *
     * @param sortnum the value for BTC_user_userCredit.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.theNote
     *
     * @return the value of BTC_user_userCredit.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.theNote
     *
     * @param thenote the value for BTC_user_userCredit.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.areaCode
     *
     * @return the value of BTC_user_userCredit.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.areaCode
     *
     * @param areacode the value for BTC_user_userCredit.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.provinceID
     *
     * @return the value of BTC_user_userCredit.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.provinceID
     *
     * @param provinceid the value for BTC_user_userCredit.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.provinceName
     *
     * @return the value of BTC_user_userCredit.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.provinceName
     *
     * @param provincename the value for BTC_user_userCredit.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.cityID
     *
     * @return the value of BTC_user_userCredit.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.cityID
     *
     * @param cityid the value for BTC_user_userCredit.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.cityName
     *
     * @return the value of BTC_user_userCredit.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.cityName
     *
     * @param cityname the value for BTC_user_userCredit.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.countyID
     *
     * @return the value of BTC_user_userCredit.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.countyID
     *
     * @param countyid the value for BTC_user_userCredit.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.countyName
     *
     * @return the value of BTC_user_userCredit.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.countyName
     *
     * @param countyname the value for BTC_user_userCredit.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.townID
     *
     * @return the value of BTC_user_userCredit.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getTownid() {
        return townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.townID
     *
     * @param townid the value for BTC_user_userCredit.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownid(Integer townid) {
        this.townid = townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BTC_user_userCredit.townName
     *
     * @return the value of BTC_user_userCredit.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getTownname() {
        return townname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BTC_user_userCredit.townName
     *
     * @param townname the value for BTC_user_userCredit.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownname(String townname) {
        this.townname = townname;
    }
}