package com.woniu.godaji.pojo;

public class BtcWareStore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_ware_store.btcWareStoreID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer btcwarestoreid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_ware_store.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer wareid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_ware_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer storeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_ware_store.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String materialid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column btc_ware_store.companyfid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String companyfid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_ware_store.btcWareStoreID
     *
     * @return the value of btc_ware_store.btcWareStoreID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getBtcwarestoreid() {
        return btcwarestoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_ware_store.btcWareStoreID
     *
     * @param btcwarestoreid the value for btc_ware_store.btcWareStoreID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBtcwarestoreid(Integer btcwarestoreid) {
        this.btcwarestoreid = btcwarestoreid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_ware_store.wareID
     *
     * @return the value of btc_ware_store.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getWareid() {
        return wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_ware_store.wareID
     *
     * @param wareid the value for btc_ware_store.wareID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setWareid(Integer wareid) {
        this.wareid = wareid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_ware_store.storeID
     *
     * @return the value of btc_ware_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getStoreid() {
        return storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_ware_store.storeID
     *
     * @param storeid the value for btc_ware_store.storeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setStoreid(Integer storeid) {
        this.storeid = storeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_ware_store.materialID
     *
     * @return the value of btc_ware_store.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getMaterialid() {
        return materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_ware_store.materialID
     *
     * @param materialid the value for btc_ware_store.materialID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setMaterialid(String materialid) {
        this.materialid = materialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column btc_ware_store.companyfid
     *
     * @return the value of btc_ware_store.companyfid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCompanyfid() {
        return companyfid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column btc_ware_store.companyfid
     *
     * @param companyfid the value for btc_ware_store.companyfid
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCompanyfid(String companyfid) {
        this.companyfid = companyfid;
    }
}