package com.woniu.godaji.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class UserInfoUserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer usergradeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer provinceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String provincename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer cityid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String cityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer countyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String countyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer townid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String townname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String usercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String loginname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.loginPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String loginpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.payPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String paypwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.nickName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userTel
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String usertel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userSex
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String usersex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.idCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userEmail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userBirthday
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date userbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userQQ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String userqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userMSN
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String usermsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userAliW
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String useraliw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userYYID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String useryyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userBlogAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String userblogadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userWWWAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String userwwwadd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userWeiChartID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String userweichartid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.balance
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.usercredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private BigDecimal usercredit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userRegDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Date userregdt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String infotype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.reCommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer recommend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.userFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer userfromsource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.transactionAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String transactionaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.financingAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String financingaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.bankNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.bankerName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String bankername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.bank
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String bank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.iszhongxin
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iszhongxin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.bankCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer sortnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private Integer iscurrent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info_userInfo.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    private String thenote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userID
     *
     * @return the value of user_info_userInfo.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userID
     *
     * @param userid the value for user_info_userInfo.userID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userGradeID
     *
     * @return the value of user_info_userInfo.userGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUsergradeid() {
        return usergradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userGradeID
     *
     * @param usergradeid the value for user_info_userInfo.userGradeID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsergradeid(Integer usergradeid) {
        this.usergradeid = usergradeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.provinceID
     *
     * @return the value of user_info_userInfo.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.provinceID
     *
     * @param provinceid the value for user_info_userInfo.provinceID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.provinceName
     *
     * @return the value of user_info_userInfo.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getProvincename() {
        return provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.provinceName
     *
     * @param provincename the value for user_info_userInfo.provinceName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setProvincename(String provincename) {
        this.provincename = provincename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.cityID
     *
     * @return the value of user_info_userInfo.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.cityID
     *
     * @param cityid the value for user_info_userInfo.cityID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityid(Integer cityid) {
        this.cityid = cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.cityName
     *
     * @return the value of user_info_userInfo.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.cityName
     *
     * @param cityname the value for user_info_userInfo.cityName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.countyID
     *
     * @return the value of user_info_userInfo.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getCountyid() {
        return countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.countyID
     *
     * @param countyid the value for user_info_userInfo.countyID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyid(Integer countyid) {
        this.countyid = countyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.countyName
     *
     * @return the value of user_info_userInfo.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getCountyname() {
        return countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.countyName
     *
     * @param countyname the value for user_info_userInfo.countyName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setCountyname(String countyname) {
        this.countyname = countyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.townID
     *
     * @return the value of user_info_userInfo.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getTownid() {
        return townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.townID
     *
     * @param townid the value for user_info_userInfo.townID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownid(Integer townid) {
        this.townid = townid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.townName
     *
     * @return the value of user_info_userInfo.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getTownname() {
        return townname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.townName
     *
     * @param townname the value for user_info_userInfo.townName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTownname(String townname) {
        this.townname = townname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.areaCode
     *
     * @return the value of user_info_userInfo.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.areaCode
     *
     * @param areacode the value for user_info_userInfo.areaCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userCode
     *
     * @return the value of user_info_userInfo.userCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUsercode() {
        return usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userCode
     *
     * @param usercode the value for user_info_userInfo.userCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.loginName
     *
     * @return the value of user_info_userInfo.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLoginname() {
        return loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.loginName
     *
     * @param loginname the value for user_info_userInfo.loginName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLoginname(String loginname) {
        this.loginname = loginname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.loginPwd
     *
     * @return the value of user_info_userInfo.loginPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getLoginpwd() {
        return loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.loginPwd
     *
     * @param loginpwd the value for user_info_userInfo.loginPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setLoginpwd(String loginpwd) {
        this.loginpwd = loginpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.payPwd
     *
     * @return the value of user_info_userInfo.payPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getPaypwd() {
        return paypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.payPwd
     *
     * @param paypwd the value for user_info_userInfo.payPwd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setPaypwd(String paypwd) {
        this.paypwd = paypwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userName
     *
     * @return the value of user_info_userInfo.userName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userName
     *
     * @param username the value for user_info_userInfo.userName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.nickName
     *
     * @return the value of user_info_userInfo.nickName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.nickName
     *
     * @param nickname the value for user_info_userInfo.nickName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userTel
     *
     * @return the value of user_info_userInfo.userTel
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUsertel() {
        return usertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userTel
     *
     * @param usertel the value for user_info_userInfo.userTel
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsertel(String usertel) {
        this.usertel = usertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userSex
     *
     * @return the value of user_info_userInfo.userSex
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userSex
     *
     * @param usersex the value for user_info_userInfo.userSex
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.idCard
     *
     * @return the value of user_info_userInfo.idCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.idCard
     *
     * @param idcard the value for user_info_userInfo.idCard
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userEmail
     *
     * @return the value of user_info_userInfo.userEmail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userEmail
     *
     * @param useremail the value for user_info_userInfo.userEmail
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userBirthday
     *
     * @return the value of user_info_userInfo.userBirthday
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getUserbirthday() {
        return userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userBirthday
     *
     * @param userbirthday the value for user_info_userInfo.userBirthday
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserbirthday(Date userbirthday) {
        this.userbirthday = userbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userQQ
     *
     * @return the value of user_info_userInfo.userQQ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUserqq() {
        return userqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userQQ
     *
     * @param userqq the value for user_info_userInfo.userQQ
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserqq(String userqq) {
        this.userqq = userqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userMSN
     *
     * @return the value of user_info_userInfo.userMSN
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUsermsn() {
        return usermsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userMSN
     *
     * @param usermsn the value for user_info_userInfo.userMSN
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsermsn(String usermsn) {
        this.usermsn = usermsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userAliW
     *
     * @return the value of user_info_userInfo.userAliW
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUseraliw() {
        return useraliw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userAliW
     *
     * @param useraliw the value for user_info_userInfo.userAliW
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUseraliw(String useraliw) {
        this.useraliw = useraliw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userYYID
     *
     * @return the value of user_info_userInfo.userYYID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUseryyid() {
        return useryyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userYYID
     *
     * @param useryyid the value for user_info_userInfo.userYYID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUseryyid(String useryyid) {
        this.useryyid = useryyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userBlogAdd
     *
     * @return the value of user_info_userInfo.userBlogAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUserblogadd() {
        return userblogadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userBlogAdd
     *
     * @param userblogadd the value for user_info_userInfo.userBlogAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserblogadd(String userblogadd) {
        this.userblogadd = userblogadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userWWWAdd
     *
     * @return the value of user_info_userInfo.userWWWAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUserwwwadd() {
        return userwwwadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userWWWAdd
     *
     * @param userwwwadd the value for user_info_userInfo.userWWWAdd
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserwwwadd(String userwwwadd) {
        this.userwwwadd = userwwwadd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userWeiChartID
     *
     * @return the value of user_info_userInfo.userWeiChartID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUserweichartid() {
        return userweichartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userWeiChartID
     *
     * @param userweichartid the value for user_info_userInfo.userWeiChartID
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserweichartid(String userweichartid) {
        this.userweichartid = userweichartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.balance
     *
     * @return the value of user_info_userInfo.balance
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.balance
     *
     * @param balance the value for user_info_userInfo.balance
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.usercredit
     *
     * @return the value of user_info_userInfo.usercredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public BigDecimal getUsercredit() {
        return usercredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.usercredit
     *
     * @param usercredit the value for user_info_userInfo.usercredit
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUsercredit(BigDecimal usercredit) {
        this.usercredit = usercredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userRegDT
     *
     * @return the value of user_info_userInfo.userRegDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Date getUserregdt() {
        return userregdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userRegDT
     *
     * @param userregdt the value for user_info_userInfo.userRegDT
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserregdt(Date userregdt) {
        this.userregdt = userregdt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userPhoto
     *
     * @return the value of user_info_userInfo.userPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userPhoto
     *
     * @param userphoto the value for user_info_userInfo.userPhoto
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.infoType
     *
     * @return the value of user_info_userInfo.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getInfotype() {
        return infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.infoType
     *
     * @param infotype the value for user_info_userInfo.infoType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setInfotype(String infotype) {
        this.infotype = infotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.reCommend
     *
     * @return the value of user_info_userInfo.reCommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.reCommend
     *
     * @param recommend the value for user_info_userInfo.reCommend
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setRecommend(Integer recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.userFromSource
     *
     * @return the value of user_info_userInfo.userFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getUserfromsource() {
        return userfromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.userFromSource
     *
     * @param userfromsource the value for user_info_userInfo.userFromSource
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setUserfromsource(Integer userfromsource) {
        this.userfromsource = userfromsource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.transactionAccount
     *
     * @return the value of user_info_userInfo.transactionAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getTransactionaccount() {
        return transactionaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.transactionAccount
     *
     * @param transactionaccount the value for user_info_userInfo.transactionAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setTransactionaccount(String transactionaccount) {
        this.transactionaccount = transactionaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.financingAccount
     *
     * @return the value of user_info_userInfo.financingAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getFinancingaccount() {
        return financingaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.financingAccount
     *
     * @param financingaccount the value for user_info_userInfo.financingAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setFinancingaccount(String financingaccount) {
        this.financingaccount = financingaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.bankNO
     *
     * @return the value of user_info_userInfo.bankNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.bankNO
     *
     * @param bankno the value for user_info_userInfo.bankNO
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBankno(String bankno) {
        this.bankno = bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.bankerName
     *
     * @return the value of user_info_userInfo.bankerName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBankername() {
        return bankername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.bankerName
     *
     * @param bankername the value for user_info_userInfo.bankerName
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBankername(String bankername) {
        this.bankername = bankername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.bank
     *
     * @return the value of user_info_userInfo.bank
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.bank
     *
     * @param bank the value for user_info_userInfo.bank
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBank(String bank) {
        this.bank = bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.iszhongxin
     *
     * @return the value of user_info_userInfo.iszhongxin
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIszhongxin() {
        return iszhongxin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.iszhongxin
     *
     * @param iszhongxin the value for user_info_userInfo.iszhongxin
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIszhongxin(Integer iszhongxin) {
        this.iszhongxin = iszhongxin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.bankCode
     *
     * @return the value of user_info_userInfo.bankCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.bankCode
     *
     * @param bankcode the value for user_info_userInfo.bankCode
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.sortNum
     *
     * @return the value of user_info_userInfo.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getSortnum() {
        return sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.sortNum
     *
     * @param sortnum the value for user_info_userInfo.sortNum
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setSortnum(Integer sortnum) {
        this.sortnum = sortnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.isDelete
     *
     * @return the value of user_info_userInfo.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.isDelete
     *
     * @param isdelete the value for user_info_userInfo.isDelete
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.isCurrent
     *
     * @return the value of user_info_userInfo.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public Integer getIscurrent() {
        return iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.isCurrent
     *
     * @param iscurrent the value for user_info_userInfo.isCurrent
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setIscurrent(Integer iscurrent) {
        this.iscurrent = iscurrent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info_userInfo.theNote
     *
     * @return the value of user_info_userInfo.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public String getThenote() {
        return thenote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info_userInfo.theNote
     *
     * @param thenote the value for user_info_userInfo.theNote
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    public void setThenote(String thenote) {
        this.thenote = thenote;
    }
}