package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcExpressprice;
import com.woniu.godaji.pojo.BtcExpresspriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcExpresspriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcExpresspriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcExpresspriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer expressrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcExpressprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcExpressprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcExpressprice> selectByExample(BtcExpresspriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcExpressprice selectByPrimaryKey(Integer expressrateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcExpressprice record, @Param("example") BtcExpresspriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcExpressprice record, @Param("example") BtcExpresspriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcExpressprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_expressPrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcExpressprice record);
}