package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcGoodsWareimg;
import com.woniu.godaji.pojo.BtcGoodsWareimgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcGoodsWareimgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcGoodsWareimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcGoodsWareimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer wareimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcGoodsWareimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcGoodsWareimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcGoodsWareimg> selectByExample(BtcGoodsWareimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcGoodsWareimg selectByPrimaryKey(Integer wareimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcGoodsWareimg record, @Param("example") BtcGoodsWareimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcGoodsWareimg record, @Param("example") BtcGoodsWareimgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcGoodsWareimg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_wareImg
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcGoodsWareimg record);
}