package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcGoodsWareprice;
import com.woniu.godaji.pojo.BtcGoodsWarepriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcGoodsWarepriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcGoodsWarepriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcGoodsWarepriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer warepriceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcGoodsWareprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcGoodsWareprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcGoodsWareprice> selectByExample(BtcGoodsWarepriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcGoodsWareprice selectByPrimaryKey(Integer warepriceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcGoodsWareprice record, @Param("example") BtcGoodsWarepriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcGoodsWareprice record, @Param("example") BtcGoodsWarepriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcGoodsWareprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_goods_warePrice
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcGoodsWareprice record);
}