package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcMarketWareclassificationtype;
import com.woniu.godaji.pojo.BtcMarketWareclassificationtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcMarketWareclassificationtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcMarketWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcMarketWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer wareclassificationtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcMarketWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcMarketWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcMarketWareclassificationtype> selectByExample(BtcMarketWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcMarketWareclassificationtype selectByPrimaryKey(Integer wareclassificationtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcMarketWareclassificationtype record, @Param("example") BtcMarketWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcMarketWareclassificationtype record, @Param("example") BtcMarketWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcMarketWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_market_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcMarketWareclassificationtype record);
}