package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcPreferentialPackages;
import com.woniu.godaji.pojo.BtcPreferentialPackagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcPreferentialPackagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcPreferentialPackagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcPreferentialPackagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer btcPpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcPreferentialPackages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcPreferentialPackages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcPreferentialPackages> selectByExample(BtcPreferentialPackagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcPreferentialPackages selectByPrimaryKey(Integer btcPpid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcPreferentialPackages record, @Param("example") BtcPreferentialPackagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcPreferentialPackages record, @Param("example") BtcPreferentialPackagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcPreferentialPackages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_Preferential_packages
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcPreferentialPackages record);
}