package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcSysWarebrand;
import com.woniu.godaji.pojo.BtcSysWarebrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcSysWarebrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcSysWarebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcSysWarebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer warebrandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcSysWarebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcSysWarebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcSysWarebrand> selectByExample(BtcSysWarebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcSysWarebrand selectByPrimaryKey(Integer warebrandid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcSysWarebrand record, @Param("example") BtcSysWarebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcSysWarebrand record, @Param("example") BtcSysWarebrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcSysWarebrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareBrand
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcSysWarebrand record);
}