package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcSysWareclassificationtype;
import com.woniu.godaji.pojo.BtcSysWareclassificationtypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcSysWareclassificationtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcSysWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcSysWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer wareclassificationtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcSysWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcSysWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcSysWareclassificationtype> selectByExample(BtcSysWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcSysWareclassificationtype selectByPrimaryKey(Integer wareclassificationtypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcSysWareclassificationtype record, @Param("example") BtcSysWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcSysWareclassificationtype record, @Param("example") BtcSysWareclassificationtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcSysWareclassificationtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_sys_wareClassificationType
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcSysWareclassificationtype record);
}