package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcUserCart;
import com.woniu.godaji.pojo.BtcUserCartExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcUserCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcUserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcUserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer usercartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcUserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcUserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcUserCart> selectByExample(BtcUserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcUserCart selectByPrimaryKey(Integer usercartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcUserCart record, @Param("example") BtcUserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcUserCart record, @Param("example") BtcUserCartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcUserCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BTC_user_cart
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcUserCart record);
}