package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.BtcWareStore;
import com.woniu.godaji.pojo.BtcWareStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BtcWareStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(BtcWareStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(BtcWareStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer btcwarestoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(BtcWareStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(BtcWareStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<BtcWareStore> selectByExample(BtcWareStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    BtcWareStore selectByPrimaryKey(Integer btcwarestoreid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") BtcWareStore record, @Param("example") BtcWareStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") BtcWareStore record, @Param("example") BtcWareStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(BtcWareStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table btc_ware_store
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(BtcWareStore record);
}