package com.woniu.godaji.mapper;

import com.woniu.godaji.pojo.UserPayPayaccount;
import com.woniu.godaji.pojo.UserPayPayaccountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPayPayaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int countByExample(UserPayPayaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByExample(UserPayPayaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int deleteByPrimaryKey(Integer payaccountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insert(UserPayPayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int insertSelective(UserPayPayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    List<UserPayPayaccount> selectByExample(UserPayPayaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    UserPayPayaccount selectByPrimaryKey(Integer payaccountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserPayPayaccount record, @Param("example") UserPayPayaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByExample(@Param("record") UserPayPayaccount record, @Param("example") UserPayPayaccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKeySelective(UserPayPayaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pay_payAccount
     *
     * @mbggenerated Tue Feb 18 00:31:41 CST 2020
     */
    int updateByPrimaryKey(UserPayPayaccount record);
}